import assert from "node:assert/strict";
import { test } from "node:test";
import { createServer } from "node:http";
import { setTimeout as delay } from "node:timers/promises";
import { createSessionRuntimeHandler } from "@cantelop/sdk/runtime";
import { createBehaviour } from "../src/session.js";
import type { handle } from "../src/worker.js";

test("activity survives message deadline, rejects concurrent work, permits inspection and cancels independently", async t => {
  let turnSignal: AbortSignal | undefined;
  let runs = 0;
  let release!: () => void;
  const work = new Promise<void>(resolve => { release = resolve; });
  const run: typeof handle = async (_root, command, messageId, _env, signal) => {
    if (command.type === "inspect") return { type: "session", messageId, data: { status: "running" } };
    if (command.type === "prompt" && command.prompt === "fail") throw new Error("private provider failure");
    runs++; turnSignal = signal;
    await work;
    return { type: "completed", messageId };
  };
  const sandbox = `sbx-${"a".repeat(32)}`;
  const server = createServer(createSessionRuntimeHandler(createBehaviour(run, 5000), { sandboxId: sandbox, executionTimeoutMs: 100 }));
  await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(() => { release(); server.closeAllConnections(); server.close(); });
  const address = server.address(); assert.ok(address && typeof address !== "string");
  const base = `http://127.0.0.1:${address.port}/__cantelop/v2`;
  const request = async (path: string, body?: unknown) => {
    const response = await fetch(base + path, { method: body === undefined ? "GET" : "POST", headers: { "x-cantelop-sandbox-id": sandbox, "content-type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
    assert.ok(response.ok, await response.clone().text());
    return response.json() as Promise<any>;
  };
  const send = (n: number, payload: unknown) => request("/messages", { session: { id: "one", workspace_id: `wsp_${"b".repeat(32)}`, keep_alive_seconds: 300 }, message: { id: `msg_${String(n).padStart(32, "0")}`, payload } });
  const receipt = await send(1, { type: "prompt", sessionId: "one", prompt: "go" });
  await delay(150);
  assert.equal((await request(`/messages/${receipt.message_id}`)).state, "succeeded");
  assert.equal(turnSignal?.aborted, false);
  assert.ok((await request("/runtime")).activity);
  await send(2, { type: "prompt", sessionId: "one", prompt: "again" });
  let events = await request("/runtime/events?after=0");
  assert.equal(events.events[0].event.data.code, "session_busy");
  await request("/runtime/events/ack", { through: events.events.at(-1).cursor });
  await send(3, { type: "inspect", sessionId: "one" });
  events = await request(`/runtime/events?after=${events.events.at(-1).cursor}`);
  assert.equal(events.events[0].event.type, "session");
  await request("/runtime/events/ack", { through: events.events.at(-1).cursor });
  assert.equal(runs, 1);
  const runtime = await request("/runtime");
  await request("/runtime/activity/cancel", { activity_id: runtime.activity.id });
  assert.equal(turnSignal?.aborted, true);
  release();
  for (let i = 0; i < 50 && (await request("/runtime")).activity; i++) await delay(10);
  assert.equal((await request("/runtime")).activity, null);
  await send(4, { type: "prompt", sessionId: "one", prompt: "retry" });
  events = await request(`/runtime/events?after=${events.events.at(-1).cursor}`);
  assert.equal(events.events[0].event.type, "completed");
  await request("/runtime/events/ack", { through: events.events.at(-1).cursor });
  assert.equal(runs, 2);
  for (let i = 0; i < 50 && (await request("/runtime")).activity; i++) await delay(10);
  const failedReceipt = await send(5, { type: "prompt", sessionId: "one", prompt: "fail" });
  events = await request(`/runtime/events?after=${events.events.at(-1).cursor}`);
  assert.equal(events.events[0].event.type, "failed");
  await request("/runtime/events/ack", { through: events.events.at(-1).cursor });
  for (let i = 0; i < 50 && (await request("/runtime")).activity; i++) await delay(10);
  assert.equal((await request(`/messages/${failedReceipt.message_id}`)).state, "succeeded");
  const observations = await request("/runtime/observations?after=0&wait=0");
  const lifecycle = observations.observations.filter((entry: any) => entry.observation.attributes?.source === "activity");
  assert.deepEqual(lifecycle.map((entry: any) => entry.observation.attributes.outcome),
    ["started", "cancellation_requested", "cancelled", "started", "completed", "started", "failed"]);
  assert.doesNotMatch(JSON.stringify(observations), /private provider failure/);
});
